movie_project/movie_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls")),
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_project/movieapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index' ),
    path('movie/<int:movie_id>',views.details,name="details"),
    path('add/',views.add,name="add"),
    path('update/<int:id>',views.update,name="update"),
    path('delete/<int:id>',views.delete,name="delete"),
    ]

movie_project/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery',default='')

    def __str__(self):
        return self.name

movie_project/movieapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movie_project/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movie_list=Movie.objects.all()
    context={
        'movie':movie_list
    }
    return render(request,'index.html',context)

def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})
    # return HttpResponse("movie no is %s" %movie_id)

def add(request):
    if request.method == 'POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']

        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'movie':movie,'form':form})

def delete(request,id):
    if request.method == "POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,"delete.html")

movie_project/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter  name">
    <input type="text" name="desc" placeholder="enter desc">
    <input type="text" name="year" placeholder="enter year">
    <input type="file" name="img">


    <input type="submit" value="submit" >

</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
{% endblock %}

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    Online movie store
  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

movie_project/templates/delete.html
<form method="POST" >

{% csrf_token %}
  are you sure to delete this?
  <input type="submit">
</form>

movie_project/templates/details.html
{% extends 'base.html'%}
{% block body %}
<img src="{{ movie.img.url }}">
{{movie.year}}
<a href="{% url 'movieapp:update' movie.id %}">update</a>
<a href="{% url 'movieapp:delete' movie.id %}">delete</a>
{% endblock %}
</body>
</html>

movie_project/templates/edit.html
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
{{form.as_p}} <!--   this form is key -->
    <input type="submit" value="submit">

</form>

movie_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
{% for i in movie %}
<img src="{{ i.img.url }} " width="100" height="100">
<a href="{% url 'movieapp:details' i.id %}" >{{i.name}}</a><br>
{% endfor %}

{% endblock %}